# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
 apt-get update && apt install -y python3-pip libpq-dev && pip3 install psycopg2 django
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-bb-vm"
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = "4"
  end
  config.vm.provision "file", source: "./testfile.txt", destination: "$HOME/testfile.txt"
  config.vm.provision "shell", inline: $script
end